//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeGenie.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HomeGenie.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to review.
        /// </summary>
        public static string About_Review_Button {
            get {
                return ResourceManager.GetString("About_Review_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if you like this app and think others might find this application useful, sharing your experience in a short review would be highly appreciated..
        /// </summary>
        public static string About_Review_Message {
            get {
                return ResourceManager.GetString("About_Review_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support.
        /// </summary>
        public static string About_Support_Button {
            get {
                return ResourceManager.GetString("About_Support_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for technical support, suggestions or comments write to info@generoso.info.
        /// </summary>
        public static string About_Support_Message {
            get {
                return ResourceManager.GetString("About_Support_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOMEGENIE - ABOUT.
        /// </summary>
        public static string About_Title_Window {
            get {
                return ResourceManager.GetString("About_Title_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to close.
        /// </summary>
        public static string Browser_Menu_Close {
            get {
                return ResourceManager.GetString("Browser_Menu_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this is the first time you run homegenie. if you did not already, download and install to your pc homegenie service from the following link:
        ///http://generoso.info/homegenie
        ///then configure homegenie client app by clicking the button below..
        /// </summary>
        public static string FirstRun_Message {
            get {
                return ResourceManager.GetString("FirstRun_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..::[ connecting to homegenie service ]::...
        /// </summary>
        public static string MainPage_Popup_Connecting {
            get {
                return ResourceManager.GetString("MainPage_Popup_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed connecting to homegenie.
        /// </summary>
        public static string MainPage_Popup_ConnectionError {
            get {
                return ResourceManager.GetString("MainPage_Popup_ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXIT.
        /// </summary>
        public static string MainPage_Popup_Exit {
            get {
                return ResourceManager.GetString("MainPage_Popup_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        public static string MainPage_Popup_Help {
            get {
                return ResourceManager.GetString("MainPage_Popup_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retry.
        /// </summary>
        public static string MainPage_Popup_Retry {
            get {
                return ResourceManager.GetString("MainPage_Popup_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string MainPage_Popup_Settings {
            get {
                return ResourceManager.GetString("MainPage_Popup_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOMEGENIE.
        /// </summary>
        public static string MainPage_Title {
            get {
                return ResourceManager.GetString("MainPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin.
        /// </summary>
        public static string Menu_AdminPage {
            get {
                return ResourceManager.GetString("Menu_AdminPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string Menu_Info {
            get {
                return ResourceManager.GetString("Menu_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to setup.
        /// </summary>
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watts.
        /// </summary>
        public static string Module_Meter_Watts {
            get {
                return ResourceManager.GetString("Module_Meter_Watts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity.
        /// </summary>
        public static string Module_Sensor_Humidity {
            get {
                return ResourceManager.GetString("Module_Sensor_Humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luminance.
        /// </summary>
        public static string Module_Sensor_Luminance {
            get {
                return ResourceManager.GetString("Module_Sensor_Luminance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string Module_Sensor_Temperature {
            get {
                return ResourceManager.GetString("Module_Sensor_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery.
        /// </summary>
        public static string Module_Status_Battery {
            get {
                return ResourceManager.GetString("Module_Status_Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Module_Status_ColorHsb {
            get {
                return ResourceManager.GetString("Module_Status_ColorHsb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Module_Status_Level {
            get {
                return ResourceManager.GetString("Module_Status_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable notifications.
        /// </summary>
        public static string Settings_EnableNotifications_Text {
            get {
                return ResourceManager.GetString("Settings_EnableNotifications_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connect.
        /// </summary>
        public static string Settings_RemoteConnect_Text {
            get {
                return ResourceManager.GetString("Settings_RemoteConnect_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string Settings_RemotePassword_Text {
            get {
                return ResourceManager.GetString("Settings_RemotePassword_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to service address.
        /// </summary>
        public static string Settings_RemoteServer_Text {
            get {
                return ResourceManager.GetString("Settings_RemoteServer_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username.
        /// </summary>
        public static string Settings_RemoteUsername_Text {
            get {
                return ResourceManager.GetString("Settings_RemoteUsername_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to homegenie service settings.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOMEGENIE - SETTINGS.
        /// </summary>
        public static string Settings_Title_Window {
            get {
                return ResourceManager.GetString("Settings_Title_Window", resourceCulture);
            }
        }
    }
}
